import type { BrandConfig } from './types';

/**
 * RMC — Rental Mobil Cengkareng
 * Cengkareng area car rental brand.
 */
export const rmcBrand: BrandConfig = {
  id: 'rmc',
  shortName: 'RMC',
  legalName: 'RMC Rental Mobil Cengkareng',
  city: 'Cengkareng',
  tagline: 'Mobil Siap Pakai, Perjalanan Lancar.',
  description:
    'Sewa mobil di Cengkareng area Bandara Soekarno-Hatta dengan mudah dan cepat. Harga tanya admin, sistem lepas kunci tanpa supir, layanan terpercaya, unit siap pakai. Dekat bandara, cocok transit & wisata.',
  siteUrl: 'https://rentalmobilcengkarengrmc.com',
  whatsappNumber: '6282329616166',
  gtmId: 'GTM-KM5GLHDW',
  adsId: 'AW-11380968042',
  logoPath: '/images/logo.png',
  ogImagePath: '/images/Hero_White_car_driving_on_road_20260919164146.webp',
  social: {
    instagram: 'https://www.instagram.com/inforentalmotorbandung/',
    tiktok: 'https://www.tiktok.com/@nethen.rental',
  },
  navLinks: [
    { href: '/armada', label: 'Armada' },
    { href: '/harga', label: 'Harga' },
    { href: '/galeri', label: 'Galeri' },
    { href: '/tentang-kami', label: 'Tentang Kami' },
    { href: '/lokasi', label: 'Lokasi' },
    { href: '/faq', label: 'FAQ' },
    { href: '/snk', label: 'S&K' },
  ],
  seoLocations: [
    { name: 'Sewa Mobil Cengkareng', href: '/sewa-mobil-cengkareng' },
    { name: 'Rental Mobil Bandara Soetta', href: '/sewa-mobil-bandara-soetta' },
    { name: 'Sewa Mobil Duri Kosambi', href: '/sewa-mobil-duri-kosambi' },
    { name: 'Rental Mobil Kapuk', href: '/sewa-mobil-kapuk' },
    { name: 'Sewa Mobil Kembangan', href: '/sewa-mobil-kembangan' },
    { name: 'Rental Mobil Tangerang', href: '/sewa-mobil-tangerang' },
    { name: 'Sewa Mobil Batusari', href: '/sewa-mobil-batusari' },
    { name: 'Rental Mobil Puri Kembangan', href: '/sewa-mobil-puri-kembangan' },
    { name: 'Sewa Mobil Joglo', href: '/sewa-mobil-joglo' },
    { name: 'Rental Mobil Meruya', href: '/sewa-mobil-meruya' },
  ],
  homepageSections: [
    'Header',
    'Hero',
    'Keunggulan',
    'Armada',
    'Proses',
    'FAQ',
    'OrderForm (#pesan)',
    'CTA',
    'Footer',
    'FloatingWhatsApp',
    'PromoPopup',
  ],
  promoPopup: {
    enabled: true,
    delayMs: 12000,
    eyebrow: 'Unit mobil terbatas hari ini',
    title: 'Pesan sekarang, keburu kehabisan!',
    description:
      'Weekend & musim liburan unit cepat ludes. Amankan mobil favorit Anda sekarang sebelum penuh.',
    primaryCta: 'Pesan Sekarang',
    secondaryCta: 'Chat WhatsApp',
    footnote: 'Respon cepat via WhatsApp · Harga tanya admin',
  },
  business: {
    streetAddress: 'Jl. KH. Hasbi Ash Shiddieq No. 88, RT.001/RW.004, Cengkareng Tim.',
    addressLocality: 'Jakarta Barat',
    addressRegion: 'DKI Jakarta',
    postalCode: '11730',
    addressCountry: 'ID',
    latitude: -6.149278,
    longitude: 106.731036,
    openingHours: 'Mo-Su 05:00-21:30',
    priceRange: 'Harga tanya admin',
  },
  theme: {
    background: '0 0% 100%',
    foreground: '0 0% 6%',
    primary: '45 100% 50%',
    primaryForeground: '0 0% 6%',
    muted: '0 0% 94%',
    mutedForeground: '0 0% 40%',
    border: '45 30% 88%',
    ring: '45 100% 50%',
    radius: '0.625rem',
    fontSans: 'Inter',
    fontDisplay: 'Plus Jakarta Sans',
  },
};